<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SharpProspero.Packager</RootNamespace>
    <AssemblyName>sharpprospero-pack</AssemblyName>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LibProsperoPkg">
      <HintPath>LibProsperoPkg.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
