<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnableInternalTests>true</EnableInternalTests>
  </PropertyGroup>

  <PropertyGroup Condition="'$(EmbedDiagnosticShaders)' == 'true'">
    <DefineConstants>$(DefineConstants);DIAGNOSTIC_SHADERS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpProspero\SharpProspero.csproj" AdditionalProperties="EnableInternalTests=true" />
    <ProjectReference Include="..\..\tools\SharpProspero.Prx\SharpProspero.Prx.csproj" AdditionalProperties="EnableInternalTests=true" />
    <ProjectReference Include="..\..\tools\SharpProspero.Link\SharpProspero.Link.csproj" AdditionalProperties="EnableInternalTests=true" />
    <ProjectReference Include="..\..\tools\SharpProspero.Texture\SharpProspero.Texture.csproj" AdditionalProperties="EnableInternalTests=true" />
  </ItemGroup>

</Project>
