source "https://rubygems.org"

# Preview with: bundle install && bundle exec jekyll serve
gem "jekyll", "~> 4.4"
gem "jekyll-remote-theme", "~> 0.5"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-relative-links", "~> 0.8"
gem "jekyll-include-cache", "~> 0.2"
gem "webrick", "~> 1.9"
