<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SharpProspero.Link</RootNamespace>
    <AssemblyName>SharpProspero.Link</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpProspero.Prx\SharpProspero.Prx.csproj" />
  </ItemGroup>

</Project>
