// SharpProspero.Prx - module inspection and stub generation.
// Copyright (C) 2026 SvenGDK

using System;
using System.Collections.Generic;
using System.Text;

namespace SharpProspero.Prx;

/// <summary>One entry point to bind: its name and an optional call signature.</summary>
/// <param name="Name">The exported function name.</param>
/// <param name="ReturnType">A C# return type, or empty to expose only the address.</param>
/// <param name="ParameterTypes">The C# parameter types, in order.</param>
public readonly record struct PrxBinding(string Name, string ReturnType, IReadOnlyList<string> ParameterTypes);

/// <summary>
/// Emits a C# wrapper that loads a module at run time and exposes its exports as unmanaged function
/// pointers. The wrapper depends only on the supplied module; the entry points are resolved from it
/// when the wrapper is loaded. A binding with a signature becomes a callable function pointer; a
/// binding without one exposes the raw address.
/// </summary>
public static class PrxBindingsEmitter
{
    /// <summary>
    /// Generates the wrapper source. <paramref name="moduleFileName"/> is the module's file name in
    /// the package (for example <c>mylib.prx</c>); <paramref name="namespaceName"/> and
    /// <paramref name="className"/> name the produced type.
    /// </summary>
    public static string Emit(
        string namespaceName, string className, string moduleFileName, IReadOnlyList<PrxBinding> bindings)
    {
        ArgumentException.ThrowIfNullOrEmpty(namespaceName);
        ArgumentException.ThrowIfNullOrEmpty(className);
        ArgumentException.ThrowIfNullOrEmpty(moduleFileName);
        ArgumentNullException.ThrowIfNull(bindings);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SharpProspero from a supplied module. Do not edit by hand.");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using SharpProspero.Modules;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>Loads <c>").Append(moduleFileName)
          .AppendLine("</c> from the package and binds its exports.</summary>");
        sb.Append("public sealed unsafe class ").Append(className).AppendLine(" : IDisposable");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly PrxModule _module;");
        sb.AppendLine();

        foreach (PrxBinding binding in bindings)
        {
            if (binding.ParameterTypes is { Count: > 0 } || !string.IsNullOrEmpty(binding.ReturnType))
                sb.Append("    /// <summary>Bound export <c>").Append(binding.Name).AppendLine("</c>.</summary>")
                  .Append("    public readonly ").Append(PointerType(binding)).Append(' ').Append(binding.Name).AppendLine(";");
            else
                sb.Append("    /// <summary>Address of export <c>").Append(binding.Name).AppendLine("</c>.</summary>")
                  .Append("    public readonly IntPtr ").Append(binding.Name).AppendLine(";");
        }

        sb.AppendLine();
        sb.Append("    private ").Append(className).AppendLine("(PrxModule module)");
        sb.AppendLine("    {");
        sb.AppendLine("        _module = module;");
        foreach (PrxBinding binding in bindings)
        {
            if (binding.ParameterTypes is { Count: > 0 } || !string.IsNullOrEmpty(binding.ReturnType))
                sb.Append("        ").Append(binding.Name).Append(" = (").Append(PointerType(binding))
                  .Append(")module.GetFunctionPointer(\"").Append(binding.Name).AppendLine("\");");
            else
                sb.Append("        ").Append(binding.Name).Append(" = module.GetExport(\"")
                  .Append(binding.Name).AppendLine("\");");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    /// <summary>Loads the module from the package's module folder.</summary>");
        sb.AppendLine();
        sb.Append("    public static ").Append(className).Append(" Load() => new(PrxModule.LoadFromPackage(\"")
          .Append(moduleFileName).AppendLine("\"));");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Unloads the module.</summary>");
        sb.AppendLine("    public void Dispose() => _module.Dispose();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string PointerType(PrxBinding binding)
    {
        var sb = new StringBuilder("delegate* unmanaged<");
        foreach (string parameter in binding.ParameterTypes ?? [])
            sb.Append(parameter).Append(", ");
        sb.Append(string.IsNullOrEmpty(binding.ReturnType) ? "void" : binding.ReturnType);
        sb.Append('>');
        return sb.ToString();
    }
}
